### PR TITLE
PHP 8.1 support

### PR DESCRIPTION
**Pull request by brad-ps**

### CODE REVIEW

**Comment by brad-ps** [comment]
Currently in the process of fully testing

**Comment by wilr** [comment]
@JZubero be great to have this merged.

**Comment by thats4shaw** [comment]
@JZubero anything we can do to help get this merged?

**Comment by JZubero** [comment]
If we are updating versions we should also upgrade `firebase/php-jwt` to >=6.0.0 to address a Sev 9.1 vulnerability.

> In Firebase PHP-JWT before 6.0.0, an algorithm-confusion issue (e.g., RS256 / HS256) exists via the kid (aka Key ID) header, when multiple types of keys are loaded in a key ring. This allows an attacker to forge tokens that validate under the incorrect key. NOTE: this provides a straightforward way to use the PHP-JWT library unsafely, but might not be considered a vulnerability in the library itself.

When having all the dependencies up to date and all tests still passing I will merge and create a new version tag.

**Comment by thats4shaw** [comment]
https://github.com/Level51/silverstripe-jwt-utils/pull/7 - combines this and `firebase-php-jwt` upgrade.

Haven't confirmed tests are passing yet but working fine on project I use this module heavily on.

**Comment by JZubero** [comment]
Closing in favor of #7

**Pull request closed without merging**
