### PR TITLE
Add class namespaces for tests

### PR DESCRIPTION
**Pull request by wilr**

### CODE REVIEW

**Comment by JZubero** [comment]
Is there any particular reason that you have removed the sqlite snippet?

**Comment by wilr** [comment]
> Is there any particular reason that you have removed the sqlite snippet?

Not really the place for it - it's better suited to either be located in the test runner configuration.

**Comment by JZubero** [comment]
Yeah, probably. If you remove the corresponding section in the README I'll merge the PR and create a new version.

**Comment by wilr** [comment]
@JZubero done. scrutinizer is erroring because it's not setup but other than that should be good :)

**Pull request merged**
